import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Button } from '@mui/material'
import BannerNeu from '@/components/moviedetails/BannerNeu'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cliffhanger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button></Button>
      <main>
        <BannerNeu></BannerNeu>
      </main>
    </>
  )
}