import Head from 'next/head'
import { Inter } from 'next/font/google'
import Button from '../components/button/Button';
import Header from '../components/header/Header/Header';
import Layout from '@/components/layout/Layout';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    
    <>
      <Head>
        <title>Cliffhanger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/8b4ae14cf9.js" crossorigin="anonymous"></script>
      </Head>
      <Layout>{
        }</Layout>
    </>
  )
}